"use client";
import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {getSupabase,isSupabaseConfigured} from '@/lib/supabase/client';
import {me} from '@/lib/api/client';
import {getMyProfile,METRIC_LABEL} from '@/lib/api/people';
import {Resource} from './resource';
import {Empty,Skeleton,Badge} from './ui';
export function Account(){const [user,setUser]=useState<User|null|undefined>(undefined);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [signup,setSignup]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{const client=getSupabase();if(!client)return;let active=true;client.auth.getSession().then(({data,error})=>{if(active){setUser(data.session?.user??null);if(error)setError('Your session could not be restored. Please sign in again.')}});const {data}=client.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null));return()=>{active=false;data.subscription.unsubscribe()}},[]);
 if(!isSupabaseConfigured())return <Empty title="Your place in the commons."><p>Account sign-in is not configured for this deployment. Connect Supabase Auth to bring your contribution history here.</p><a className="button" href="/setup">Go to setup ↗</a></Empty>;
 if(user===undefined)return <Skeleton/>;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const fields=new FormData(e.currentTarget);const client=getSupabase()!;try{const credentials={email:String(fields.get('email')),password:String(fields.get('password'))};const result=signup?await client.auth.signUp({...credentials,options:{emailRedirectTo:window.location.origin+'/auth/callback'}}):await client.auth.signInWithPassword(credentials);if(result.error)throw result.error;if(signup&&!result.data.session)setNotice('Check your email to confirm your account.');}catch{setError('We couldn’t complete sign-in. Check your details and try again.')}finally{setBusy(false)}}
 if(!user)return <div className="auth-layout"><div><p className="eyebrow">A LITTLE LESS STARTING OVER</p><h2>{signup?'Make yourself at home.':'Welcome back.'}</h2><p>Keep your procedures, claims, and contributions together.</p><a href="/docs/privacy">How we handle your data ↗</a></div><form onSubmit={submit} className="auth-form"><label>Email<input type="email" name="email" autoComplete="email" required /></label><label>Password<input type="password" name="password" minLength={8} autoComplete={signup?'new-password':'current-password'} required aria-describedby={error?'auth-error':undefined}/></label>{error&&<p id="auth-error" role="alert" className="warning">{error}</p>}{notice&&<p role="status">{notice}</p>}<button className="button" disabled={busy}>{busy?'One moment…':signup?'Create account ↗':'Sign in ↗'}</button><button className="text-button" type="button" onClick={()=>{setSignup(!signup);setError('');setNotice('')}}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button></form></div>;
 return <><div className="identity"><div><p className="eyebrow">SIGNED IN</p><h2>{user.email}</h2></div><button className="button secondary" onClick={async()=>{const {error}=await getSupabase()!.auth.signOut();if(error)setError('Sign-out failed. Please try again.')}}>Sign out</button></div>{error&&<p role="alert">{error}</p>}<section><h2>Your contribution to the commons.</h2><Resource load={getMyProfile}>{p=><><div className="metrics">{Object.entries(p.counts).map(([k,v])=><div key={k}><strong>{v}</strong><span>{METRIC_LABEL[k as keyof typeof METRIC_LABEL]}</span></div>)}</div><p><Badge>{p.profile?.visibility || 'private'} profile</Badge> Public visibility is opt-in.</p></>}</Resource></section><Resource load={me}>{data=><><section className="section compact"><h2>Your procedures</h2>{data.submitted_procedures.length?<ul className="activity">{data.submitted_procedures.map(p=><li key={p.id}><a href={'/procedures/'+encodeURIComponent(p.id)}>{p.name} ↗</a><Badge>{p.verification_state}</Badge></li>)}</ul>:<p className="callout">No procedures yet. Connect your agent to contribute your first useful approach.</p>}</section><section><h2>Your claims</h2>{data.submitted_claims.length?<ul>{data.submitted_claims.map(c=><li key={c.id}>{c.name}</li>)}</ul>:<p>No claims contributed yet.</p>}</section><section className="section compact"><h2>Execution history</h2>{data.executions.length?<ul className="activity">{data.executions.map(e=><li key={e.id}><span>Execution {e.id.slice(0,8)}</span><Badge>{e.outcome || 'Outcome pending'}</Badge><span>{e.started_at?new Date(e.started_at).toLocaleDateString():''}</span></li>)}</ul>:<p>No execution history available.</p>}</section></>}</Resource></>;
}
