"use client";
import {useCallback,useState} from 'react';
import {listProblems,problem,leaderboard,evaluations} from '@/lib/api/client';
import {getContributorLeaderboard, LEADERBOARD_METRICS, METRIC_LABEL, type LeaderboardMetric} from '@/lib/api/people';
import {Resource} from './resource';
import {Badge,Empty,PageHead} from './ui';
export function Problems({query}:{query:string}){const load=useCallback(()=>listProblems(query),[query]);return <Resource load={load}>{rows=>rows.length?<><p className="muted">{rows.length} problems{rows.length===200?' · showing the first 200; search to narrow your results':''}</p><div className="problem-list">{rows.map((p,i)=><a className="problem-row" key={p.id} href={'/problems/'+encodeURIComponent(p.id)}><span className="index">{String(i+1).padStart(2,'0')}</span><div><h2>{p.title}</h2><p>{p.description || p.objective || 'Explore the approaches and evidence for this problem.'}</p><span className="muted">{p.proposer?'Proposed by '+p.proposer:'Compare related approaches'}</span></div><Badge>{p.status}</Badge><span aria-hidden="true">↗</span></a>)}</div></>:<Empty title={query?'No matching problems yet.':'A place for the next good question.'}><p>{query?'Try another phrase, or search for a procedure directly.':'There are no problems available in this library yet. Search for a procedure to get started.'}</p><a href="/search">Search the knowledge library ↗</a></Empty>}</Resource>}
export function Contributors(){const [metric,setMetric]=useState<LeaderboardMetric>('verified_procedures');const load=useCallback(()=>getContributorLeaderboard(metric),[metric]);return <section className="contributors"><div className="list-heading"><div><p className="eyebrow">THE PEOPLE BEHIND THE PROGRESS</p><h2>Contributions that count.</h2></div><label>Measure<select value={metric} onChange={e=>setMetric(e.target.value as LeaderboardMetric)}>{LEADERBOARD_METRICS.map(m=><option key={m} value={m}>{METRIC_LABEL[m]}</option>)}</select></label></div><p className="muted">Only contributors who have chosen a public profile appear here.</p><Resource key={metric} load={load}>{data=>data.entries.length?<ol className="contributor-list">{data.entries.map(e=><li key={e.user_id}><div><strong>{e.display_name}</strong><p>{e.tagline}</p></div><span>{e.value} <small>{METRIC_LABEL[data.metric].toLowerCase()}</small></span></li>)}</ol>:<Empty title="Room for the first contribution."><p>No public contributors for this measure yet.</p></Empty>}</Resource></section>}
export function ProblemDetail({id}:{id:string}){const load=useCallback(()=>problem(id),[id]);return <Resource load={load}>{p=><><PageHead eyebrow="THE COMMONS / PROBLEM" title={p.title}>{p.description || p.objective}</PageHead><div className="meta-line"><Badge>{p.status}</Badge>{p.proposer && <span>Proposed by {p.proposer}</span>}<span>Updated {new Date(p.updated_at).toLocaleDateString()}</span></div><Ranking id={id}/><EvaluationList id={id}/><section className="callout"><h2>Help improve this problem.</h2><p>Contribute a procedure or report a real execution through your connected agent. Evidence supports the specific version tested.</p><a href="/setup">Connect to contribute ↗</a></section></>}</Resource>}
function Ranking({id}:{id:string}){const load=useCallback(()=>leaderboard(id),[id]);return <section className="section compact"><div className="list-heading"><h2>Ways forward.</h2><span>Evidence, before confidence.</span></div><Resource load={load}>{data=>data.leaderboard.length?<><p>{data.current_best.length ? (data.current_best_is_tie?'The leading approaches are tied.':'The current best is highlighted below.'):'No approach has enough evidence to be called the current best.'}</p><p className="muted">Ranked by the backend using comparable evaluations. Different conditions can change the result.</p>{data.leaderboard.map((entry,i)=><article className={'ranking '+(data.current_best.includes(entry.solution_id)?'best':'')} key={entry.solution_id}><span className="rank">{String(i+1).padStart(2,'0')}</span><div><Badge>{entry.state.replaceAll('_',' ').toLowerCase()}</Badge><h3>{entry.solution_type==='procedure'?<a href={'/procedures/'+encodeURIComponent(entry.target_id)}>Procedure {entry.target_id.slice(0,8)} ↗</a>:<span>{entry.solution_type} {entry.target_id.slice(0,8)}</span>}</h3><p>{entry.verified_successes} verified successes · {entry.run_count} runs · {entry.evaluations} evaluations</p><details><summary>Inspect comparison</summary><p>Verified success rate: {entry.verified_success_rate===null?'Not available':(entry.verified_success_rate*100).toFixed(1)+'%'}</p><p>Wilson confidence interval: {(entry.verified_success_wilson_lower*100).toFixed(1)}–{(entry.verified_success_wilson_upper*100).toFixed(1)}%</p><p>{entry.incomparable_evaluations} evaluations excluded from comparison.</p>{entry.p50_latency_s!==null && <p>Median latency: {entry.p50_latency_s}s</p>}</details></div></article>)}</>:<Empty title="No best way established. "><p>Approaches need comparable evaluation evidence before a ranking can take shape.</p><a href="/setup">Help build the evidence ↗</a></Empty>}</Resource></section>}
function EvaluationList({id}:{id:string}){const load=useCallback(()=>evaluations(id),[id]);return <section><h2>Evidence & activity</h2><Resource load={load}>{rows=>rows.length?<ul className="activity">{rows.map(e=><li key={e.id}><Badge>{e.status}</Badge><div><strong>Evaluation {e.id.slice(0,8)}</strong><p>Benchmark {e.benchmark_id.slice(0,8)}{e.procedure_version?' · Procedure version '+e.procedure_version:''}</p>{e.provenance && <p>Source: {e.provenance}</p>}<details><summary>Tested conditions</summary><dl>{Object.entries(e.environment).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></details></div></li>)}</ul>:<p className="callout">No evaluation history available yet.</p>}</Resource></section>}
