"""Offline: the structural half of the code cascade (S1 filters, S2/S3 span features, scoring, import graph, funnel).

No network, no model, no database. Every expectation here was first observed on a real repository (click, express, chi, ky) and
is pinned on a small synthetic file so the behaviour cannot drift silently."""
from __future__ import annotations

import pytest

from app.services.code_cascade import graph, inventory, python_features, scoring, treesitter_features
from app.services.code_cascade.cascade import run_structural_cascade

PY_HARD = '''
import re


def parse_range(text, lo=0, hi=100):
    """Parse '1-5,8,10-12' into a sorted list of ints, clamped to [lo, hi]."""
    out = set()
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        m = re.match(r"^(\\d+)-(\\d+)$", part)
        if m:
            a, b = int(m.group(1)), int(m.group(2))
            if a > b:
                raise ValueError(f"reversed range {part!r}")
            for n in range(max(a, lo), min(b, hi) + 1):
                out.add(n)
        elif part.isdigit():
            n = int(part)
            if lo <= n <= hi:
                out.add(n)
        else:
            raise ValueError(f"bad token {part!r}")
    return sorted(out)


class Box:
    def get(self):
        return self._x

    def set(self, v):
        self._x = v

    def wrap(self):
        return parse_range(self.text)

    def todo(self):
        raise NotImplementedError
'''


# ------------------------------------------------------------------------------------------------ S1 inventory

@pytest.mark.parametrize("path,reason", [
    ("node_modules/x/index.js", "vendored_generated_or_boilerplate_path"),
    ("src/api_pb2.py", "vendored_generated_or_boilerplate_path"),
    ("web/app.min.js", "vendored_generated_or_boilerplate_path"),
    ("pkg/__init__.py", "vendored_generated_or_boilerplate_path"),
    ("README.md", "not_source_code"),
    ("assets/logo.png", "not_source_code"),
])
def test_paths_that_can_never_be_exemplars_are_dropped_before_any_bytes_are_read(path, reason):
    assert inventory.path_verdict(path).reason == reason


def test_content_gates_catch_generated_binary_minified_and_tiny_files():
    body = "value_number_one = compute_the_thing(argument)  # padding to clear the minimum size\n" * 30
    assert inventory.content_verdict("a.py", "# @generated by protoc\n" + body).reason == "generated_marker"
    assert inventory.content_verdict("a.py", "\x00" + body).reason == "binary"
    assert inventory.content_verdict("a.js", "var a=1;" * 200).reason == "minified_or_data_blob"
    assert inventory.content_verdict("a.py", "x = 1\n").reason in {"too_small", "too_few_lines"}
    assert inventory.content_verdict("a.py", "def f():\n    return 1\n" * 30).kept


def test_tests_and_examples_survive_with_a_role_and_are_not_dropped():
    assert inventory.role_of("tests/test_x.py") == "test"
    assert inventory.role_of("src/thing.test.ts") == "test"
    assert inventory.role_of("examples/basic/app.js") == "example"
    assert inventory.role_of("src/core.py") == "source"
    assert inventory.path_verdict("tests/test_x.py").kept and inventory.path_verdict("examples/a.js").kept


# ------------------------------------------------------------------------------------------- S2 python features

def test_python_plumbing_is_named_and_real_logic_is_not():
    by_name = {s.name: s for s in python_features.extract_spans(PY_HARD)}
    assert by_name["parse_range"].trivial_reason is None
    # Box holds a getter, a setter, a delegate and a stub: however many branches its parts sum to, it teaches nothing
    assert by_name["Box"].trivial_reason == "plumbing_class"
    single = python_features.extract_spans("def get_x(o):\n    return o._x\n\ndef todo():\n    raise NotImplementedError\n")
    assert all(s.trivial_reason for s in single), "a getter and an abstract stub are plumbing"


def test_a_class_with_real_logic_in_one_method_is_not_plumbing():
    src = ("class A:\n    def get(self):\n        return self._x\n\n    def real(self, xs):\n        t = 0\n"
           "        for x in xs:\n            if x > 1 and x < 9:\n                t += x\n            elif x < 0:\n"
           "                t -= 1\n        return t\n")
    spans = python_features.extract_spans(src)
    assert spans[0].kind == "class" and spans[0].trivial_reason is None


def test_python_complexity_features_are_counted():
    f = {s.name: s for s in python_features.extract_spans(PY_HARD)}["parse_range"]
    assert f.cyclomatic >= 8 and f.max_nesting >= 3 and f.has_loop and f.has_docstring and f.uses_regex_or_bitops
    assert f.distinct_calls >= 6 and f.kind == "function" and f.line_start < f.line_end


def test_copy_pasted_python_with_renamed_variables_has_an_equal_fingerprint():
    a = "def f(xs):\n    t = 0\n    for x in xs:\n        if x > 1:\n            t += x\n    return t\n"
    b = "def g(items):\n    total = 0\n    for item in items:\n        if item > 9:\n            total += item\n    return total\n"
    assert python_features.extract_spans(a)[0].fingerprint == python_features.extract_spans(b)[0].fingerprint
    c = a.replace("if x > 1:", "while x > 1:")
    assert python_features.extract_spans(c)[0].fingerprint != python_features.extract_spans(a)[0].fingerprint


def test_python_syntax_errors_yield_no_spans_not_an_exception():
    assert python_features.extract_spans("def broken(:\n  pass") == []
    assert python_features.module_imports("def broken(:\n  pass") == set()


# ---------------------------------------------------------------------------------------- S2 tree-sitter features

JS_SRC = '''
/** Retry with backoff. */
export const retry = async (fn, attempts = 5) => {
  let delay = 100
  for (let i = 0; i < attempts; i++) {
    try { return await fn(i) }
    catch (err) {
      if (i === attempts - 1 || !err.retryable) throw err
      await sleep(delay * (1 + Math.random()))
      delay = Math.min(delay * 2, 10000)
    }
  }
}

res.send = function send(body) {
  var chunk = body
  if (typeof chunk === 'string') { this.set('Content-Type', 'text/html') }
  else if (Buffer.isBuffer(chunk)) { this.set('Content-Type', 'application/octet-stream') }
  else if (chunk !== null) { return this.json(chunk) }
  return this.end(chunk)
}

const api = { fetchAll: async function (ids) { const out = []; for (const id of ids) { if (!id) continue; out.push(await get(id)) } return out } }

function getName() { return this.name }
'''

GO_SRC = '''package q

// Run drains the queue until ctx is done.
func (s *S) Run(ctx context.Context, n int) error {
	defer s.mu.Unlock()
	for i := 0; i < n; i++ {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case job := <-s.jobs:
			if job == nil || job.done {
				continue
			}
			go s.handle(job)
		}
	}
	return nil
}

func (s *S) Name() string { return s.name }
'''


def test_js_finds_arrow_assignment_and_object_pair_functions_and_names_them():
    spans = {s.name: s for s in treesitter_features.extract_spans(JS_SRC, "javascript")}
    assert {"retry", "send", "fetchAll", "getName"} <= set(spans)
    assert spans["retry"].is_async and spans["retry"].has_loop and spans["retry"].has_docstring
    assert spans["retry"].cyclomatic >= 5 and spans["send"].cyclomatic >= 4
    assert spans["getName"].trivial_reason is not None, "a getter is plumbing"
    assert spans["send"].trivial_reason is None


def test_assignment_style_span_includes_its_whole_statement():
    send = {s.name: s for s in treesitter_features.extract_spans(JS_SRC, "javascript")}["send"]
    line = JS_SRC.splitlines()[send.line_start - 1]
    assert line.startswith("res.send = function send"), "the span starts at the assignment, not mid-expression"


def test_go_select_defer_and_goroutines_are_recognised():
    spans = {s.name: s for s in treesitter_features.extract_spans(GO_SRC, "go")}
    run = spans["Run"]
    assert run.has_loop and run.is_async and run.uses_context_manager and run.has_docstring
    assert run.cyclomatic >= 5 and run.max_nesting >= 2
    assert spans["Name"].trivial_reason is not None


def test_a_file_with_syntax_errors_is_skipped_whole_not_scored_from_a_partial_tree():
    assert treesitter_features.extract_spans("function ( {{{ nope", "javascript") == []
    assert treesitter_features.extract_spans("anything", "cobol") == []


# ------------------------------------------------------------------------------------------------------- scoring

def _span(**over):
    base = dict(name="f", kind="function", line_start=1, line_end=40, code_lines=30, cyclomatic=8, max_nesting=3,
                distinct_calls=8, branches=7, has_loop=True, has_recursion=False, is_async=False, is_generator=False,
                uses_context_manager=False, uses_regex_or_bitops=False, has_docstring=True, annotated_fraction=0.0,
                trivial_reason=None, fingerprint="x")
    base.update(over)
    return python_features.SpanFeatures(**base)


def test_plumbing_scores_exactly_zero_not_low():
    assert scoring.span_score(_span(trivial_reason="pure_delegate")) == 0.0


def test_more_decisions_nesting_and_variety_score_higher():
    base = scoring.span_score(_span())
    assert scoring.span_score(_span(cyclomatic=20)) > base
    assert scoring.span_score(_span(max_nesting=4)) > scoring.span_score(_span(max_nesting=1))
    assert scoring.span_score(_span(distinct_calls=15)) > scoring.span_score(_span(distinct_calls=2))
    assert scoring.span_score(_span(has_recursion=True)) > base


def test_the_size_window_rejects_snippets_too_small_or_too_large_for_a_small_model():
    assert scoring.size_window(4) == 0.0 and scoring.size_window(200) == 0.0
    assert scoring.size_window(30) == 1.0
    assert 0.0 < scoring.size_window(10) < 1.0 and 0.0 < scoring.size_window(120) < 1.0


def test_role_weights_put_source_before_examples_before_tests():
    assert scoring.ROLE_WEIGHT["source"] > scoring.ROLE_WEIGHT["example"] > scoring.ROLE_WEIGHT["test"]


# ---------------------------------------------------------------------------------------------------- import graph

def test_python_relative_and_absolute_imports_resolve_inside_the_repo():
    files = {
        "src/pkg/core.py": ("x = 1\n", "python"),
        "src/pkg/util.py": ("from . import core\n", "python"),
        "src/pkg/cli.py": ("from pkg.util import helper\nimport requests\n", "python"),
        "src/pkg/other.py": ("from .core import x\n", "python"),
    }
    indeg = graph.build_indegree(files)
    assert indeg.get("src/pkg/core.py") == 2
    assert indeg.get("src/pkg/util.py") == 1
    assert "requests" not in indeg


def test_js_relative_imports_reexports_and_require_resolve_with_extensions_and_index():
    files = {
        "src/a.ts": ("import { b } from './b'\nexport * from './lib'\nconst c = require('./c.js')\nimport x from 'lodash'\n", "typescript"),
        "src/b.ts": ("export const b = 1\n", "typescript"),
        "src/lib/index.ts": ("export const l = 1\n", "typescript"),
        "src/c.ts": ("export const c = 1\n", "typescript"),
        "src/d.ts": ("import { b } from './b'\n", "typescript"),
    }
    indeg = graph.build_indegree(files)
    assert indeg["src/b.ts"] == 2 and indeg["src/lib/index.ts"] == 1
    assert indeg["src/c.ts"] == 1, "a compiled .js specifier resolves to its .ts source"


def test_go_imports_resolve_through_the_repository_module_name():
    files = {
        "go.mod": ("module github.com/acme/app\n\ngo 1.22\n", "go"),
        "cmd/main.go": ('package main\nimport (\n  "fmt"\n  "github.com/acme/app/pkg/util"\n)\n', "go"),
        "pkg/util/util.go": ("package util\n", "go"),
        "pkg/util/util_test.go": ("package util\n", "go"),
        "pkg/other/o.go": ('package other\nimport "github.com/acme/app/pkg/util"\n', "go"),
    }
    indeg = graph.build_indegree({p: v for p, v in files.items() if p.endswith(".go")}, go_mod_text=files["go.mod"][0])
    assert indeg["pkg/util/util.go"] == 2 and "pkg/util/util_test.go" not in indeg


# ---------------------------------------------------------------------------------------------------------- cascade

def test_the_cascade_reports_every_stage_and_keeps_only_non_trivial_source_first():
    repo = {
        "src/core.py": PY_HARD,
        "src/other.py": PY_HARD.replace("parse_range", "parse_span").replace("Box", "Crate"),
        "src/widget.js": JS_SRC,
        "tests/test_core.py": PY_HARD.replace("parse_range", "parse_test_range"),
        "vendor/big.py": PY_HARD,
        "README.md": "# hi\n" * 50,
        "src/data.rs": "fn x() {}\n" * 20,
    }
    result = run_structural_cascade(repo, max_spans=10, per_file=2)
    funnel = result.funnel.as_dict()
    assert funnel["files_in"] == 7 and funnel["s1_dropped"]["vendored_generated_or_boilerplate_path"] == 1
    assert funnel["s1_dropped"]["not_source_code"] == 1
    assert funnel["spans_plumbing"], "getters/delegates/stubs are counted, not silently lost"
    assert funnel["spans_duplicate"] >= 1, "the renamed copy in other.py is the same structure"
    kept = result.kept
    assert kept and all(k.ranked.score > 0 for k in kept)
    names = [k.ranked.features.name for k in kept]
    assert len(names) == len(set(k.ranked.features.fingerprint for k in kept)), "no two kept spans share a structure"
    assert {"retry", "send"} <= set(names) or {"send", "fetchAll"} <= set(names)
    source_first = [k.ranked.role for k in kept]
    assert source_first.index("source") < (source_first.index("test") if "test" in source_first else 99)
    for k in kept:
        assert k.text.splitlines()[0].strip() == inventory_first_line(repo[k.path], k)


def inventory_first_line(text: str, k) -> str:
    return text.splitlines()[k.line_start - 1].strip()


def test_per_file_cap_prevents_one_file_from_flooding_the_result():
    many = "\n".join(
        f"def f{i}(xs):\n    t = 0\n    for x in xs:\n        if x > {i}:\n            t += x * {i}\n        elif x < -{i}:\n            t -= 1\n    return t\n"
        .replace("x * ", "int(x) * ") + ("    # pad\n" * (i % 3)) for i in range(12))
    # distinct structures so the copy-paste dedupe does not thin them: vary the shape
    varied = []
    for i in range(12):
        body = "".join(f"    if xs[{j}] > {i}:\n        xs[{j}] += 1\n" for j in range(i % 5 + 2))
        varied.append(f"def g{i}(xs):\n    total = 0\n    for x in xs:\n        total += x\n{body}    return total\n")
    result = run_structural_cascade({"src/big.py": "\n".join(varied)}, max_spans=50, per_file=3)
    assert len(result.kept) <= 3
    assert result.funnel.files_with_kept_spans == 1
